[package]
name = "huffman"
version = "0.2.0"
authors = ["bit doer <bitdoer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.21.0"
itertools = "0.10.0"